'use client';
import {useEffect,useState} from 'react';
import {Battery,Home,Sun,Wifi,Zap} from 'lucide-react';
import {EnergyFlow} from '@/components/EnergyFlow';
import type {Telemetry} from '@/lib/types';
import {emptyTelemetry} from '@/lib/types';
import {dailyEnergy} from '@/lib/energy';
type History={timestamp:string;solarPowerW:number|null;loadPowerW:number|null};

function amp(value:number|null){return value===null?'--':Math.abs(value).toFixed(1)}
function derivedAmp(powerW:number|null,voltageV:number|null){
 if(powerW===null||voltageV===null||voltageV<=0)return null;
 return Math.abs(powerW/voltageV);
}

export default function Dashboard(){
 const [telemetry,setTelemetry]=useState<Telemetry>(emptyTelemetry);const [history,setHistory]=useState<History[]>([]);
 useEffect(()=>{let active=true;const load=async()=>{try{const[a,b]=await Promise.all([fetch('/api/telemetry',{cache:'no-store'}),fetch('/api/history?hours=24',{cache:'no-store'})]);if(a.ok&&active)setTelemetry(await a.json());if(b.ok&&active){const d=await b.json();setHistory(Array.isArray(d.items)?d.items:[])}}catch{}};load();const id=window.setInterval(load,10000);return()=>{active=false;window.clearInterval(id)}},[]);
 const online=telemetry.source==='gateway'&&Boolean(telemetry.timestamp);const energy=dailyEnergy(history);const hasEnergy=history.length>1&&(energy.solarKwh>0||energy.loadKwh>0);const solar=telemetry.solarPowerW===null?'--':(telemetry.solarPowerW/1000).toFixed(2);const load=telemetry.loadPowerW===null?'--':(telemetry.loadPowerW/1000).toFixed(2);const batt=telemetry.batterySoc===null?'--':telemetry.batterySoc.toFixed(0);
 const solarCurrent=telemetry.pvCurrentA;const homeCurrent=telemetry.outputApparentPowerVA!==null&&telemetry.outputVoltageV!==null&&telemetry.outputVoltageV>0?derivedAmp(telemetry.outputApparentPowerVA,telemetry.outputVoltageV):derivedAmp(telemetry.loadPowerW,telemetry.outputVoltageV);const batteryCurrent=telemetry.batteryCurrentA;
 return <><h1 className="page-title">المنزل</h1><p className="page-subtitle">نظرة واضحة على طاقة منزلك الآن</p><div className={`offline-banner ${online?'online-banner':''}`}><Wifi size={15}/><span>{online?'القراءة الحية متاحة من المنظومة':'لا توجد قراءة حية متاحة حالياً. تحقق من اتصال الإنفرتر وإرسال بيانات القياس.'}</span></div><div className="card" style={{marginBottom:12}}><EnergyFlow telemetry={telemetry}/></div><div className="grid-3" style={{marginBottom:12}}><div className="metric-card"><div className="metric-head"><Sun size={15}/> الشمس</div><div className="metric-value-stack"><div className="metric-value" style={{color:online?'#D99A2B':'#9A8D82'}}>{solar} <small>kW</small></div><div className="metric-current"><strong>{amp(solarCurrent)}</strong> A</div></div></div><div className="metric-card"><div className="metric-head"><Home size={15}/> المنزل</div><div className="metric-value-stack"><div className="metric-value" style={{color:online?'#B56D4D':'#9A8D82'}}>{load} <small>kW</small></div><div className="metric-current"><strong>{amp(homeCurrent)}</strong> A</div></div></div><div className="metric-card"><div className="metric-head"><Battery size={15}/> البطارية</div><div className="metric-value-stack"><div className="metric-value" style={{color:online?'#16866A':'#9A8D82'}}>{batt} <small>%</small></div><div className="metric-current"><strong>{amp(batteryCurrent)}</strong> A</div></div></div></div><div className="card" style={{marginBottom:12}}><h2 className="section-title">ملخص اليوم</h2><div className="grid-3"><div><div className="muted">إنتاج اليوم</div><strong className="value">{hasEnergy?energy.solarKwh.toFixed(2):'--'} <span className="unit">kWh</span></strong></div><div><div className="muted">استهلاك اليوم</div><strong className="value">{hasEnergy?energy.loadKwh.toFixed(2):'--'} <span className="unit">kWh</span></strong></div><div><div className="muted">وفر اليوم</div><strong className="value">-- <span className="unit">ل.س</span></strong></div></div></div><div className="card"><h2 className="section-title"><Zap size={17} color="#D99A2B"/> حالة الإنفرتر</h2><div className="grid-3"><div><span className="muted">المصدر</span><div>{online&&telemetry.inverterState?telemetry.inverterState:'--'}</div></div><div><span className="muted">الحمل</span><div>{telemetry.loadPowerW===null?'--':`${(telemetry.loadPowerW/8200*100).toFixed(0)}%`}</div></div><div><span className="muted">الحرارة</span><div>{telemetry.inverterTemperatureC===null?'--':`${telemetry.inverterTemperatureC.toFixed(0)}°C`}</div></div></div><div className="muted" style={{fontSize:11,marginTop:10}}>أولوية المصدر: شمس → بطارية → شبكة (SBU)</div></div></>;
}
