'use client';
import {useEffect,useState} from 'react';
import {ChevronDown,Sun,Gauge,Battery,Wifi,Bell,Database,PlugZap,Wallet} from 'lucide-react';

const Section=({icon,title,children}:{icon:React.ReactNode,title:string,children:React.ReactNode})=><details className="accordion" style={{marginBottom:10}}><summary><span className="section-summary"><span className="section-summary-main">{icon}<span>{title}</span></span><ChevronDown size={16} style={{color:'#90a4ae'}}/></span></summary><div className="accordion-content">{children}</div></details>;

type SettingsData={panels:string;model:string;serial:string;ratedPower:string;protocol:string;pvMaxPower:string;pvMaxVoltage:string;pvInputRange:string;mpptRange:string;acVoltage:string;batteryVoltageRange:string;batteryType:string;batteryCapacity:string;reserve:string;gatewayUrl:string;gatewayToken:string;low:string;critical:string;offline:string;retention:string;gridTariff:string;systemCost:string};
const defaults:SettingsData={panels:'',model:'Victor Max-8.2KWM',serial:'92085230517098',ratedPower:'8200 W / 8200 VA',protocol:'PI30',pvMaxPower:'8200 W',pvMaxVoltage:'500 VDC',pvInputRange:'90–450 VDC',mpptRange:'360–450 VDC',acVoltage:'220 / 230 / 240 VAC',batteryVoltageRange:'40–63 VDC',batteryType:'',batteryCapacity:'',reserve:'20%',gatewayUrl:'',gatewayToken:'',low:'20%',critical:'10%',offline:'10 دقائق',retention:'365',gridTariff:'',systemCost:''};

export default function Settings(){
 const [data,setData]=useState<SettingsData>(defaults);const [saved,setSaved]=useState(false);const [testing,setTesting]=useState(false);const [testMessage,setTestMessage]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem('solar_settings');if(raw){const parsed={...defaults,...JSON.parse(raw)};if(parsed.model==='Axpert MAX 7200-48-230'||parsed.serial==='92932009104508'){parsed.model=defaults.model;parsed.serial=defaults.serial;parsed.ratedPower=defaults.ratedPower;parsed.pvMaxPower=defaults.pvMaxPower;parsed.pvMaxVoltage=defaults.pvMaxVoltage;parsed.pvInputRange=defaults.pvInputRange;parsed.mpptRange=defaults.mpptRange;parsed.acVoltage=defaults.acVoltage;parsed.batteryVoltageRange=defaults.batteryVoltageRange;}setData(parsed)}}catch{}},[]);
 const set=(key:keyof SettingsData,value:string)=>{setData(current=>({...current,[key]:value}));setSaved(false)};
 function save(){localStorage.setItem('solar_settings',JSON.stringify(data));setSaved(true);}
 async function testConnection(){setTesting(true);setTestMessage('');try{const response=await fetch('/api/connection/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({serial_port:data.serial,baudrate:2400,timeout_ms:2000})});const result=await response.json().catch(()=>({message:'تعذر قراءة نتيجة الاختبار'}));setTestMessage(result.message??(result.ok?'تم الاتصال':'فشل الاتصال'))}catch{setTestMessage('تعذر الوصول إلى خدمة الاتصال.')}finally{setTesting(false)}}
 return <>
  <h1 className="page-title">الإعدادات</h1><p className="page-subtitle">تهيئة المنظومة والاتصال والتنبيهات</p>
  <Section icon={<Sun size={18} color="#f59e0b"/>} title="الألواح الشمسية"><div className="field"><span>إجمالي قدرة الألواح</span><input value={data.panels} onChange={e=>set('panels',e.target.value)} placeholder="مثال: 6 kW"/></div></Section>
  <Section icon={<Gauge size={18} color="#f59e0b"/>} title="الإنفرتر"><div className="field"><span>الطراز</span><input value={data.model} onChange={e=>set('model',e.target.value)}/></div><div className="field"><span>الرقم التسلسلي SN</span><input value={data.serial} onChange={e=>set('serial',e.target.value)} inputMode="numeric"/></div><div className="field"><span>القدرة الاسمية</span><input value={data.ratedPower} onChange={e=>set('ratedPower',e.target.value)}/></div><div className="field"><span>البروتوكول</span><select value={data.protocol} onChange={e=>set('protocol',e.target.value)}><option>PI30</option></select></div><div className="grid-2"><div className="field"><span>أقصى قدرة PV</span><input value={data.pvMaxPower} onChange={e=>set('pvMaxPower',e.target.value)}/></div><div className="field"><span>أقصى جهد PV</span><input value={data.pvMaxVoltage} onChange={e=>set('pvMaxVoltage',e.target.value)}/></div></div><div className="field"><span>مدى دخل PV</span><input value={data.pvInputRange} onChange={e=>set('pvInputRange',e.target.value)}/></div><div className="field"><span>مدى MPPT</span><input value={data.mpptRange} onChange={e=>set('mpptRange',e.target.value)}/></div><div className="field"><span>خرج AC الاسمي</span><input value={data.acVoltage} onChange={e=>set('acVoltage',e.target.value)}/></div></Section>
  <Section icon={<Battery size={18} color="#26a69a"/>} title="البطارية"><div className="field"><span>نطاق جهد البطارية</span><input value={data.batteryVoltageRange} onChange={e=>set('batteryVoltageRange',e.target.value)}/></div><div className="field"><span>نوع البطارية</span><select value={data.batteryType} onChange={e=>set('batteryType',e.target.value)}><option value="">-- غير محدد</option><option>LiFePO4</option><option>ليثيوم</option><option>جل</option><option>رصاص</option></select></div><div className="field"><span>السعة</span><input value={data.batteryCapacity} onChange={e=>set('batteryCapacity',e.target.value)} placeholder="مثال: 4.8 kWh"/></div><div className="field"><span>حد الاحتياطي</span><input value={data.reserve} onChange={e=>set('reserve',e.target.value)}/></div></Section>
  <Section icon={<Wifi size={18} color="#29b6f6"/>} title="الاتصال والبوابة"><div className="field"><span>وضع الاتصال</span><select defaultValue="local"><option value="local">بوابة محلية</option><option value="offline">غير متصل</option></select></div><div className="field"><span>Gateway URL</span><input value={data.gatewayUrl} onChange={e=>set('gatewayUrl',e.target.value)} placeholder="مثال: http://192.168.1.50:8787"/></div><div className="field"><span>Gateway Token</span><input type="password" value={data.gatewayToken} onChange={e=>set('gatewayToken',e.target.value)} placeholder="••••••••"/></div></Section>
  <Section icon={<PlugZap size={18} color="#26a69a"/>} title="اختبار الاتصال"><p className="muted" style={{fontSize:11}}>الاختبار يرسل طلب PI30 حقيقياً إلى البوابة ولا يولّد بيانات وهمية.</p><button className="primary-btn" onClick={testConnection} disabled={testing}>{testing?'جارٍ اختبار الاتصال...':'اختبار الاتصال بالإنفرتر'}</button>{testMessage&&<p style={{fontSize:11,textAlign:'center',color:testMessage.includes('بنجاح')?'#28724b':'#8b6500'}}>{testMessage}</p>}</Section>
  <Section icon={<Wallet size={18} color="#ab47bc"/>} title="المال والتعرفة"><div className="field"><span>تعرفة الشبكة</span><input value={data.gridTariff} onChange={e=>set('gridTariff',e.target.value)} placeholder="ل.س لكل kWh" inputMode="decimal"/></div><div className="field"><span>تكلفة النظام</span><input value={data.systemCost} onChange={e=>set('systemCost',e.target.value)} placeholder="ل.س" inputMode="decimal"/></div></Section>
  <Section icon={<Bell size={18} color="#ef5350"/>} title="التنبيهات"><div className="grid-2"><div className="field"><span>بطارية منخفضة</span><input value={data.low} onChange={e=>set('low',e.target.value)}/></div><div className="field"><span>حرج</span><input value={data.critical} onChange={e=>set('critical',e.target.value)}/></div></div><div className="field"><span>انقطاع الاتصال</span><input value={data.offline} onChange={e=>set('offline',e.target.value)}/></div></Section>
  <Section icon={<Database size={18} color="#ab47bc"/>} title="البيانات"><div className="field"><span>مدة حفظ البيانات</span><select value={data.retention} onChange={e=>set('retention',e.target.value)}><option value="365">365 يوم</option><option value="180">180 يوم</option><option value="90">90 يوم</option></select></div></Section>
  <button className="primary-btn" onClick={save}>{saved?'تم حفظ الإعدادات ✓':'حفظ الإعدادات'}</button>{saved&&<p style={{textAlign:'center',fontSize:11,color:'#26a69a'}}>تم حفظ الإعدادات على هذا الجهاز.</p>}
 </>
}
